remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: MURAYAMA Yohei
description: Software Engineer, Android and Java.
lang: ja_JP
google_analytics: UA-2234396-1
repository: mura/stoic.jp
